import { useMemo, useState, useEffect } from 'react';
import { useDocumentStore } from '../store';
import { 
  Database, Filter, Search, FileText, AlignLeft, 
  Table as TableIcon, Image as ImageIcon, Hash, Tag,
  Heading, Braces, Layers, ChevronRight, Sparkles, Settings2, Loader2,
  SlidersHorizontal
} from 'lucide-react';
import { cn } from '../components/ui';

type ChunkType = 'Title' | 'Text' | 'Table' | 'Image' | 'Formula';

interface ChunkData {
  id: string;
  docId: string;
  docName: string;
  type: ChunkType;
  content: string;
  page: number;
  tokens: number;
  entities: string[];
  vectorId: string;
}

const CHUNK_ICONS: Record<ChunkType, any> = {
  Title: Heading,
  Text: AlignLeft,
  Table: TableIcon,
  Image: ImageIcon,
  Formula: Braces,
};

const CHUNK_COLORS: Record<ChunkType, string> = {
  Title: 'text-purple-400 bg-purple-400/10 border-purple-400/20',
  Text: 'text-blue-400 bg-blue-400/10 border-blue-400/20',
  Table: 'text-emerald-400 bg-emerald-400/10 border-emerald-400/20',
  Image: 'text-amber-400 bg-amber-400/10 border-amber-400/20',
  Formula: 'text-pink-400 bg-pink-400/10 border-pink-400/20',
};

// Generate mock chunks based on MinerU parsing and RAG pipeline
const generateMockChunks = (docId: string, docName: string) => {
  const chunks: ChunkData[] = [];
  const chunkCount = 20 + Math.floor(Math.random() * 30);
  
  let currentPage = 1;
  const topics = ['GraphRAG Architecture', 'Data Processing', 'Entity Extraction', 'Performance Evaluation'];
  
  for (let i = 0; i < chunkCount; i++) {
    if (i > 0 && i % 5 === 0) currentPage++;
    
    let type: ChunkType = 'Text';
    let content = `This is a simulated text chunk extracted from page ${currentPage} of ${docName}. It contains detailed descriptions about various system components and their interactions within the RAG pipeline.`;
    let tokens = 100 + Math.floor(Math.random() * 200);
    let entities = ['RAG Pipeline', 'System Component'];

    const rand = Math.random();
    if (i === 0 || rand < 0.1) {
      type = 'Title';
      content = `${currentPage}. ${topics[i % topics.length]} Overview`;
      tokens = 10 + Math.floor(Math.random() * 20);
      entities = [topics[i % topics.length]];
    } else if (rand < 0.25) {
      type = 'Table';
      content = `| Metric | Value | Baseline |\n|--------|-------|----------|\n| Precision | 0.95 | 0.82 |\n| Recall | 0.91 | 0.78 |\n| F1 Score | 0.93 | 0.80 |`;
      tokens = 80 + Math.floor(Math.random() * 50);
      entities = ['Precision', 'Recall', 'F1 Score', 'Metrics'];
    } else if (rand < 0.35) {
      type = 'Image';
      content = `[Image description generated by Vision Model: A flowchart illustrating the data processing pipeline, starting from document ingestion, MinerU structural parsing, tokenization, to vector embedding and knowledge graph entity linking.]`;
      tokens = 50 + Math.floor(Math.random() * 40);
      entities = ['MinerU', 'Data Pipeline', 'Knowledge Graph'];
    } else if (rand < 0.4) {
      type = 'Formula';
      content = `$$ Similarity(A, B) = \\frac{A \\cdot B}{\\|A\\| \\|B\\|} $$`;
      tokens = 30 + Math.floor(Math.random() * 20);
      entities = ['Cosine Similarity', 'Vector Math'];
    }

    chunks.push({
      id: `chunk-${docId}-${i}`,
      docId,
      docName,
      type,
      content,
      page: currentPage,
      tokens,
      entities,
      vectorId: `vec_${Math.random().toString(36).substring(2, 10)}_${Date.now().toString(36)}`
    });
  }
  
  return chunks;
};

export default function VectorVisualizerPage() {
  const documents = useDocumentStore(state => state.documents);
  const readyDocs = documents.filter(d => d.status === 'READY');
  
  // App States
  const [viewMode, setViewMode] = useState<'browse' | 'search'>('browse');
  
  // Browse Mode States
  const [selectedDocId, setSelectedDocId] = useState<string | null>(readyDocs[0]?.id || null);
  const [selectedTypes, setSelectedTypes] = useState<Set<ChunkType>>(new Set(['Title', 'Text', 'Table', 'Image', 'Formula']));
  const [browseQuery, setBrowseQuery] = useState('');

  // Search Mode States
  const [searchQuery, setSearchQuery] = useState('');
  const [isSearching, setIsSearching] = useState(false);
  const [searchResults, setSearchResults] = useState<{chunk: ChunkData, score: number}[]>([]);
  const [topK, setTopK] = useState(5);
  const [alpha, setAlpha] = useState(0.5); // Hybrid weight (0: Keyword only, 1: Vector only)

  // Global Mocks Generation
  const allChunks = useMemo(() => {
    return readyDocs.flatMap(doc => generateMockChunks(doc.id, doc.name));
  }, [readyDocs]);

  // Handle doc selection update
  useEffect(() => {
    if (readyDocs.length > 0 && (!selectedDocId || !readyDocs.find(d => d.id === selectedDocId))) {
      setSelectedDocId(readyDocs[0].id);
    }
  }, [readyDocs, selectedDocId]);

  // Derived Browse Data
  const currentDocChunks = useMemo(() => {
    if (!selectedDocId) return [];
    return allChunks.filter(c => c.docId === selectedDocId);
  }, [selectedDocId, allChunks]);

  const filteredChunks = useMemo(() => {
    return currentDocChunks.filter(chunk => {
      const matchType = selectedTypes.has(chunk.type);
      const matchSearch = browseQuery ? chunk.content.toLowerCase().includes(browseQuery.toLowerCase()) : true;
      return matchType && matchSearch;
    });
  }, [currentDocChunks, selectedTypes, browseQuery]);

  const toggleType = (type: ChunkType) => {
    const next = new Set(selectedTypes);
    if (next.has(type)) {
      next.delete(type);
    } else {
      next.add(type);
    }
    setSelectedTypes(next);
  };

  // Perform Mock Search
  const handleSearch = () => {
    if (!searchQuery.trim()) {
      setSearchResults([]);
      return;
    }

    setIsSearching(true);
    // Simulate network and processing delay
    setTimeout(() => {
      // Create a copy of all chunks to sort
      let pool = [...allChunks];
      
      // Shuffle to make it look "randomly distributed" across docs
      pool = pool.sort(() => 0.5 - Math.random());
      
      // Slice Top K
      const results = pool.slice(0, topK).map((chunk, index) => {
        // Base score varies from 0.70 to 0.99
        let baseScore = 0.99 - (index * 0.04) - (Math.random() * 0.03);
        
        // Adjust score based on alpha (just for visual variation in the UI mock)
        if (alpha < 0.2) baseScore -= 0.1; // Keyword only might have lower semantic scores
        
        return { chunk, score: Math.max(0.65, baseScore) };
      });
      
      // Sort by score descending
      setSearchResults(results.sort((a, b) => b.score - a.score));
      setIsSearching(false);
    }, 800);
  };

  if (readyDocs.length === 0) {
    return (
      <div className="flex-1 flex flex-col items-center justify-center bg-[#0F1117] h-full">
        <Database className="w-16 h-16 text-[#2D3148] mb-4" />
        <h2 className="text-xl font-bold text-[#F0F2FF] mb-2">暂无向量索引数据</h2>
        <p className="text-[#8B90AC]">请先在知识库中上传并处理文档，完成后即可浏览切分块与进行检索测试</p>
      </div>
    );
  }

  const renderChunkCard = (chunk: ChunkData, index: number, score?: number) => {
    const Icon = CHUNK_ICONS[chunk.type];
    return (
      <div 
        key={`${chunk.id}-${index}`} 
        className="bg-[#1A1D27] border border-[#2D3148] rounded-xl overflow-hidden hover:border-[#4A5070] transition-colors flex flex-col min-h-[140px]"
      >
        {/* Chunk Header */}
        <div className="flex items-center justify-between px-4 py-3 border-b border-[#2D3148] bg-[#14161E] shrink-0">
          <div className="flex items-center gap-3">
            <span className="text-[#4A5070] font-mono text-sm w-10">#{index + 1}</span>
            <div className={cn("flex items-center gap-1.5 px-2 py-1 rounded text-xs font-medium border", CHUNK_COLORS[chunk.type])}>
              <Icon className="w-3.5 h-3.5" />
              {chunk.type}
            </div>
            {viewMode === 'search' ? (
              <span className="text-[#8B90AC] text-sm flex items-center gap-1 truncate max-w-[150px]" title={chunk.docName}>
                <FileText className="w-3.5 h-3.5" /> {chunk.docName}
              </span>
            ) : (
              <span className="text-[#8B90AC] text-sm flex items-center gap-1">
                <FileText className="w-3.5 h-3.5" /> 第 {chunk.page} 页
              </span>
            )}
          </div>
          <div className="flex items-center gap-3">
            {score !== undefined && (
              <div className="flex items-center gap-1 px-2 py-1 bg-emerald-500/10 text-emerald-400 border border-emerald-500/20 rounded-md text-xs font-medium">
                <Sparkles className="w-3 h-3" />
                {(score * 100).toFixed(1)}% 匹配
              </div>
            )}
            <span className="text-xs text-[#8B90AC] flex items-center gap-1 hidden sm:flex" title="Token 数量">
              <AlignLeft className="w-3.5 h-3.5" /> {chunk.tokens}
            </span>
          </div>
        </div>

        {/* Chunk Content */}
        <div className="flex-1 p-4 bg-[#0F1117] flex flex-col justify-center">
          {chunk.type === 'Table' ? (
            <pre className="text-sm text-[#F0F2FF] font-mono overflow-x-auto p-3 bg-[#1A1D27] rounded border border-[#2D3148]">
              {chunk.content}
            </pre>
          ) : chunk.type === 'Title' ? (
            <h4 className="text-lg font-bold text-[#F0F2FF]">{chunk.content}</h4>
          ) : chunk.type === 'Formula' ? (
            <div className="text-center p-4 bg-[#1A1D27] rounded border border-[#2D3148] font-serif text-[#F0F2FF] text-lg">
              {chunk.content}
            </div>
          ) : chunk.type === 'Image' ? (
            <div className="p-4 bg-[#1A1D27] border border-[#2D3148] border-dashed rounded text-[#8B90AC] text-sm flex items-start gap-3">
              <ImageIcon className="w-5 h-5 shrink-0 text-[#4A5070]" />
              <span className="italic">{chunk.content}</span>
            </div>
          ) : (
            <p className="text-sm text-[#F0F2FF] leading-relaxed">
              {chunk.content}
            </p>
          )}
        </div>

        {/* Chunk Footer (Vector & Entities) */}
        <div className="px-4 py-3 bg-[#14161E] border-t border-[#2D3148] flex flex-col sm:flex-row sm:items-center justify-between gap-3 shrink-0">
          <div className="flex items-center gap-2 overflow-hidden">
            <Hash className="w-3.5 h-3.5 text-[#4A5070] shrink-0" />
            <span className="text-xs font-mono text-[#8B90AC] truncate">
              {chunk.vectorId}
            </span>
          </div>
          
          {chunk.entities.length > 0 && (
            <div className="flex items-center gap-2 flex-wrap">
              <Tag className="w-3.5 h-3.5 text-[#7C6FE0]" />
              {chunk.entities.map((entity, i) => (
                <span 
                  key={i} 
                  className="text-[10px] px-2 py-0.5 rounded bg-[#2D3148] text-[#F0F2FF] border border-[#4A5070]/50"
                >
                  {entity}
                </span>
              ))}
            </div>
          )}
        </div>
      </div>
    );
  };

  return (
    <div className="flex flex-col md:flex-row h-full w-full bg-[#0F1117] overflow-hidden">
      {/* Left Sidebar Control Panel */}
      <div className="w-full md:w-[320px] flex-none border-b md:border-b-0 md:border-r border-[#2D3148] bg-[#1A1D27] flex flex-col z-10">
        
        {/* Mode Switcher */}
        <div className="p-4 border-b border-[#2D3148]">
          <div className="flex bg-[#0F1117] border border-[#2D3148] rounded-lg p-1">
            <button
              onClick={() => setViewMode('browse')}
              className={cn(
                "flex-1 py-1.5 text-sm font-medium rounded-md flex items-center justify-center gap-2 transition-colors",
                viewMode === 'browse' ? "bg-[#2D3148] text-[#F0F2FF]" : "text-[#8B90AC] hover:text-[#F0F2FF]"
              )}
            >
              <Layers className="w-4 h-4" /> 切分浏览
            </button>
            <button
              onClick={() => setViewMode('search')}
              className={cn(
                "flex-1 py-1.5 text-sm font-medium rounded-md flex items-center justify-center gap-2 transition-colors",
                viewMode === 'search' ? "bg-[#7C6FE0] text-white" : "text-[#8B90AC] hover:text-[#F0F2FF]"
              )}
            >
              <Search className="w-4 h-4" /> 混合检索
            </button>
          </div>
        </div>

        {/* --- Sidebar Content: Browse Mode --- */}
        {viewMode === 'browse' && (
          <div className="flex-1 overflow-y-auto p-4 space-y-6 flex flex-col">
            <div className="relative">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-[#8B90AC]" />
              <input 
                type="text" 
                placeholder="在当前文档内搜索..." 
                value={browseQuery}
                onChange={(e) => setBrowseQuery(e.target.value)}
                className="w-full bg-[#0F1117] border border-[#2D3148] rounded-md py-2 pl-9 pr-3 text-sm text-[#F0F2FF] placeholder:text-[#4A5070] focus:outline-none focus:border-[#7C6FE0] transition-colors"
              />
            </div>
            
            {/* Document Selector */}
            <div>
              <h3 className="text-sm font-semibold text-[#8B90AC] mb-3 flex items-center gap-2">
                <FileText className="w-4 h-4" /> 选择解析文档
              </h3>
              <div className="space-y-2">
                {readyDocs.map(doc => (
                  <button
                    key={doc.id}
                    onClick={() => setSelectedDocId(doc.id)}
                    className={cn(
                      "w-full text-left px-3 py-2 text-sm rounded-lg border transition-all truncate",
                      selectedDocId === doc.id
                        ? "bg-[#21253A] border-[#7C6FE0] text-[#F0F2FF]"
                        : "bg-[#0F1117] border-[#2D3148] text-[#8B90AC] hover:border-[#4A5070] hover:text-[#F0F2FF]"
                    )}
                  >
                    {doc.name}
                  </button>
                ))}
              </div>
            </div>

            {/* Type Filter */}
            <div>
              <h3 className="text-sm font-semibold text-[#8B90AC] flex items-center gap-2 mb-3">
                <Filter className="w-4 h-4" /> 结构类型过滤 (MinerU)
              </h3>
              <div className="space-y-2">
                {(Object.keys(CHUNK_ICONS) as ChunkType[]).map(type => {
                  const Icon = CHUNK_ICONS[type];
                  const count = currentDocChunks.filter(c => c.type === type).length;
                  if (count === 0) return null;

                  return (
                    <button
                      key={type}
                      onClick={() => toggleType(type)}
                      className={cn(
                        "w-full flex items-center justify-between px-3 py-2 text-sm rounded transition-colors border",
                        selectedTypes.has(type)
                          ? "bg-[#0F1117] border-[#4A5070] text-[#F0F2FF]"
                          : "bg-[#0F1117] border-transparent text-[#4A5070] opacity-50 hover:opacity-80"
                      )}
                    >
                      <div className="flex items-center gap-2">
                        <Icon className="w-4 h-4" />
                        <span>{type}</span>
                      </div>
                      <span className="text-xs bg-[#1A1D27] px-2 py-0.5 rounded border border-[#2D3148]">
                        {count}
                      </span>
                    </button>
                  );
                })}
              </div>
            </div>
            
            <div className="mt-auto pt-4 border-t border-[#2D3148]">
               <div className="text-xs text-[#4A5070] flex justify-between items-center px-1">
                 <span>当前总块数:</span>
                 <strong className="text-[#F0F2FF]">{currentDocChunks.length}</strong>
               </div>
            </div>
          </div>
        )}

        {/* --- Sidebar Content: Search Mode --- */}
        {viewMode === 'search' && (
          <div className="flex-1 overflow-y-auto p-4 space-y-6 flex flex-col">
            
            <div>
              <h3 className="text-sm font-semibold text-[#F0F2FF] mb-4 flex items-center gap-2">
                <Settings2 className="w-4 h-4 text-[#7C6FE0]" /> 检索参数配置
              </h3>
              
              <div className="space-y-6">
                {/* Top K */}
                <div className="space-y-3">
                  <div className="flex justify-between items-center text-sm">
                    <label className="text-[#8B90AC]">召回数量 (Top K)</label>
                    <span className="text-[#F0F2FF] font-mono">{topK}</span>
                  </div>
                  <input 
                    type="range" 
                    min="1" max="20" step="1" 
                    value={topK}
                    onChange={(e) => setTopK(parseInt(e.target.value))}
                    className="w-full accent-[#7C6FE0]"
                  />
                  <div className="flex justify-between text-xs text-[#4A5070]">
                    <span>1</span>
                    <span>20</span>
                  </div>
                </div>

                {/* Alpha */}
                <div className="space-y-3">
                  <div className="flex justify-between items-center text-sm">
                    <label className="text-[#8B90AC]">混合检索权重 (α)</label>
                    <span className="text-[#F0F2FF] font-mono">{alpha.toFixed(2)}</span>
                  </div>
                  <input 
                    type="range" 
                    min="0" max="1" step="0.05" 
                    value={alpha}
                    onChange={(e) => setAlpha(parseFloat(e.target.value))}
                    className="w-full accent-[#7C6FE0]"
                  />
                  <div className="flex justify-between text-xs text-[#4A5070]">
                    <span>关键词主导</span>
                    <span>向量主导</span>
                  </div>
                </div>
              </div>
            </div>

            <div className="mt-auto pt-4 border-t border-[#2D3148] space-y-3">
               <div className="p-3 bg-purple-500/10 border border-purple-500/20 rounded-lg">
                 <div className="flex items-center gap-2 text-sm text-purple-300 mb-1">
                   <Sparkles className="w-4 h-4" />
                   Hybrid Search 优势
                 </div>
                 <p className="text-xs text-purple-400/70 leading-relaxed">
                   结合了 BM25 稀疏检索的关键词命中率，以及基于 Embedding 的稠密向量检索的语义理解能力。
                 </p>
               </div>
               
               <div className="text-xs text-[#4A5070] flex justify-between items-center px-1">
                 <span>全库可检索块数:</span>
                 <strong className="text-[#F0F2FF]">{allChunks.length}</strong>
               </div>
            </div>
          </div>
        )}
      </div>

      {/* Main Content Area */}
      <div className="flex-1 bg-[#0B0D13] relative flex flex-col min-w-0">
        
        {/* Header - Browse Mode */}
        {viewMode === 'browse' && (
          <div className="p-6 border-b border-[#2D3148] bg-[#0F1117] flex justify-between items-center shrink-0">
            <div>
              <h3 className="text-[#F0F2FF] font-medium text-lg flex items-center gap-2 truncate max-w-md">
                {readyDocs.find(d => d.id === selectedDocId)?.name}
              </h3>
              <div className="text-sm text-[#8B90AC] mt-1 flex items-center gap-2">
                <span>MinerU 结构化解析 & RAG Pipeline 处理完成</span>
                <span className="px-1.5 py-0.5 rounded-full bg-emerald-400/10 text-emerald-400 border border-emerald-400/20 text-xs shrink-0">
                  已索引至 Vector Store
                </span>
              </div>
            </div>
            <div className="text-sm text-[#4A5070] bg-[#1A1D27] px-3 py-1.5 rounded-lg border border-[#2D3148] shrink-0">
              当前显示 <strong className="text-[#F0F2FF]">{filteredChunks.length}</strong> 块
            </div>
          </div>
        )}

        {/* Header - Search Mode */}
        {viewMode === 'search' && (
          <div className="p-6 border-b border-[#2D3148] bg-[#0F1117] shrink-0">
            <h3 className="text-xl font-bold text-[#F0F2FF] mb-4">全库混合检索测试</h3>
            <div className="flex gap-3">
              <div className="relative flex-1">
                <Search className="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-[#8B90AC]" />
                <input 
                  type="text" 
                  placeholder="尝试输入任意问题，如: What is GraphRAG?" 
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                  onKeyDown={(e) => e.key === 'Enter' && handleSearch()}
                  className="w-full bg-[#1A1D27] border border-[#2D3148] rounded-xl py-3.5 pl-12 pr-4 text-[#F0F2FF] placeholder:text-[#4A5070] focus:outline-none focus:border-[#7C6FE0] focus:ring-1 focus:ring-[#7C6FE0] transition-all text-base"
                />
              </div>
              <button 
                onClick={handleSearch}
                disabled={isSearching || !searchQuery.trim()}
                className="px-6 py-3.5 bg-[#7C6FE0] hover:bg-[#6A5DD3] text-white rounded-xl font-medium transition-colors disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-2"
              >
                {isSearching ? <Loader2 className="w-5 h-5 animate-spin" /> : <Sparkles className="w-5 h-5" />}
                检索
              </button>
            </div>
          </div>
        )}

        {/* List Content */}
        <div className="flex-1 overflow-y-auto p-6 grid grid-cols-1 xl:grid-cols-2 gap-4 content-start">
          
          {/* Browse Mode Results */}
          {viewMode === 'browse' && (
            filteredChunks.length === 0 ? (
              <div className="flex flex-col items-center justify-center h-40 text-[#4A5070] col-span-1 xl:col-span-2 mt-20">
                <Filter className="w-8 h-8 mb-2 opacity-50" />
                <p>没有找到符合条件的切分块</p>
              </div>
            ) : (
              filteredChunks.map((chunk, index) => renderChunkCard(chunk, index))
            )
          )}

          {/* Search Mode Results */}
          {viewMode === 'search' && (
            isSearching ? (
              <div className="flex flex-col items-center justify-center h-40 text-[#4A5070] col-span-1 xl:col-span-2 mt-20">
                <Loader2 className="w-8 h-8 mb-4 animate-spin text-[#7C6FE0]" />
                <p>正在执行向量运算与 BM25 检索...</p>
              </div>
            ) : searchResults.length > 0 ? (
              <>
                <div className="col-span-1 xl:col-span-2 mb-2 flex items-center text-sm text-[#8B90AC]">
                  <SlidersHorizontal className="w-4 h-4 mr-2" />
                  共召回 {searchResults.length} 个高度匹配的知识块片段
                </div>
                {searchResults.map((result, index) => renderChunkCard(result.chunk, index, result.score))}
              </>
            ) : searchQuery.trim() && searchResults.length === 0 ? (
              <div className="flex flex-col items-center justify-center h-40 text-[#4A5070] col-span-1 xl:col-span-2 mt-20">
                <Search className="w-8 h-8 mb-2 opacity-50" />
                <p>未找到匹配的结果</p>
              </div>
            ) : (
              <div className="flex flex-col items-center justify-center h-40 text-[#4A5070] col-span-1 xl:col-span-2 mt-20 opacity-50">
                <Database className="w-12 h-12 mb-4" />
                <p>输入关键词进行全库向量与关键词混合检索测试</p>
              </div>
            )
          )}
        </div>
      </div>
    </div>
  );
}